---
pool: 
  vmImage: "Default"
trigger: 
  - main
steps: 
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      feedRestore: 'projectName/feedName'
      projects: ./MusicStore/MusicStore.csproj
      includeNuGetOrg: true 

